Revert "RHEVM-2842: make Engine.db to work with remote db"
this is causing failure

 def setup(self):
        """
            Run setup package
            """
        assert not self.setup_done
        if self._setup is None:
            self.setup_done = True
            return
    
        if self._setup_exc is not None:
>           raise self._setup_exc
E           AttributeError: 'str' object has no attribute 'db'

pytest_customization/_pytest_art/package_fixtures.py:95: AttributeError

This reverts commit 67b1676cc652aa55900335d2385eccf66f75ce15.

Change-Id: Ic9030294da9ace308119353e897a05ba8d769ee5
Reviewed-on: https://code.engineering.redhat.com/gerrit/97106
Reviewed-by: Nelly Credi <ncredi@redhat.com>
Tested-by: Nelly Credi <ncredi@redhat.com>